<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hand">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="hand" params="connected_to:='' ns:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">
    <xacro:unless value="${connected_to == ''}">
      <joint name="${ns}_hand_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${ns}_hand"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>
    <link name="${ns}_hand">
      <visual>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/hand.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0.04" rpy="0 ${pi/2} ${pi/2}"/>
        <geometry>
          <cylinder radius="${0.04+safety_distance}" length="0.1" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 -0.05 0.04" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.04+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.05 0.04" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.04+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.1" rpy="0 ${pi/2} ${pi/2}"/>
        <geometry>
          <cylinder radius="${0.02+safety_distance}" length="0.1" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 -0.05 0.1" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.02+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.05 0.1" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.02+safety_distance}"  />
        </geometry>
      </collision>
    </link>
    <link name="${ns}_leftfinger">
      <visual>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/finger.dae"/>
        </geometry>
      </visual>
    </link>
    <link name="${ns}_rightfinger">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/finger.dae"/>
        </geometry>
      </visual>
   </link>
    <joint name="${ns}_finger_joint1" type="prismatic">
      <parent link="${ns}_hand"/>
      <child link="${ns}_leftfinger"/>
      <origin xyz="0 0 0.0584" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="20" lower="0.0" upper="0.04" velocity="0.2"/>
    </joint>
    <joint name="${ns}_finger_joint2" type="prismatic">
      <parent link="${ns}_hand"/>
      <child link="${ns}_rightfinger"/>
      <origin xyz="0 0 0.0584" rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <limit effort="20" lower="0.0" upper="0.04" velocity="0.2"/>
      <mimic joint="${ns}_finger_joint1" />
    </joint>

        <!-- OBJECT POSITION-->
    <joint name="${ns}_object_joint" type="fixed" >
      <parent link="${ns}_hand" />
      <child link="${ns}_object_link" />

      <origin xyz="0 0 0.1274" rpy="0 0 0"/>
      <!--xyz="0 0 0.1034" rpy="0 0 0" -->  
      <!-- Base delle dita 0.0584-->
   </joint>

    <link name="${ns}_object_link">
      <visual>
        <geometry>
          <box size="0.0 0.00 0.0"/>
        </geometry>
	      <material name="silver" />
      </visual>

      <collision>
        <geometry>
          <box size="0.00 0.00 0.0"/>
        </geometry>
	      <material name="black"/>
     </collision>
    </link>
      <joint name="gripper_camera_joint" type="fixed" >
      <parent link="${ns}_hand" />
      <child link="gripper_camera" />
     <!-- <origin xyz="0 0 0.0" rpy="0 ${3*pi/2} ${pi/2}"/> -->
     <!--origin xyz=" 0.04576 0.00275  0.076854" rpy="0.033641884557 -0.013806793567 1.57762792946"/-->
     <!--origin xyz=" 0.04276 -0.00275  0.076854" rpy="0.033641884557 -0.013806793567 1.57762792946"/-->

     <origin xyz=" 0.04276 0.002  0.065" rpy="0.033641884557 -0.013806793567 1.57762792946"/>
   </joint>

   <link name="gripper_camera">
      <visual>
         <geometry>
            <box size="0.0 0.00 0.0"/>
         </geometry>
	      <material name="silver" />
      </visual>
   </link>


   <joint name="realsense_camera_joint" type="fixed" >
      <parent link="${ns}_hand" />
      <child link="realsense_optical_frame" />
     <origin xyz=" -0.04276 -0.00275  0.076854" rpy="0.033641884557 -0.013806793567 1.57762792946"/>
   </joint>

   <link name="realsense_optical_frame">
      <visual>
         <geometry>
            <box size="0.0 0.00 0.0"/>
         </geometry>
	      <material name="silver" />
      </visual>
   </link>




    <joint name="gripper_realsense_joint" type="fixed" >
    <parent link="${ns}_hand" />
    <child link="camera_link" />


    <origin xyz=" -0.039278 -0.012625  0.076519" rpy= "${180*pi/180} ${-90*pi/180} 0.0" />
     <!-- "${-1.049392*pi/180} ${-4.432421*pi/180} ${91.376356*pi/180}" -->
     <!--"0.033641884557 -0.013806793567 1.57762792946"  -->
   </joint>

   <link name="camera_link">
      <visual>
         <geometry>
            <box size="0.0 0.00 0.0"/>
         </geometry>
	      <material name="silver" />
      </visual>
   </link>






   <joint name="gripper_camera_visu_joint" type="fixed" >
      <parent link="gripper_camera" />
      <child link="gripper_camera_visu" />
     <origin xyz=" 0.03 0.075 -0.01" rpy="-${pi/2}  0.0 ${pi} "/>
   </joint>

   <link name="gripper_camera_visu">
      <visual>
         <geometry>
            <mesh filename="package://franka_description/meshes/Fotocamera_gripper.STL" scale="0.001 0.001 0.001"/>
         </geometry>
	      <material name="black">
            <color rgba="0.5 0.5 0.5 1"/>
         </material>
      </visual>
   </link>






  </xacro:macro>
</robot>
